//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Turuncu.UserManagerModule.Application.Models;
using QuickCode.Turuncu.UserManagerModule.Domain.Entities;
using QuickCode.Turuncu.UserManagerModule.Application.Dtos;
using System.Threading.Tasks;

namespace QuickCode.Turuncu.UserManagerModule.Application.Interfaces.Repositories
{
    public partial interface IPortalPermissionTypesRepository : IBaseRepository<PortalPermissionTypes>
    {
        Task<DLResponse<PortalPermissionTypes>> GetByPkAsync(int id);
        Task<DLResponse<List<PortalPermissionTypesPortalPermissionGroups_RESTResponseDto>>> PortalPermissionTypesPortalPermissionGroups_RESTAsync(int portalPermissionTypesId);
        Task<DLResponse<PortalPermissionTypesPortalPermissionGroups_KEY_RESTResponseDto>> PortalPermissionTypesPortalPermissionGroups_KEY_RESTAsync(int portalPermissionTypesId, int portalPermissionGroupsId);
    }
}