//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Turuncu.EmailManagerModule.Application.Models;
using QuickCode.Turuncu.EmailManagerModule.Domain.Entities;
using QuickCode.Turuncu.EmailManagerModule.Application.Dtos;
using System.Threading.Tasks;

namespace QuickCode.Turuncu.EmailManagerModule.Application.Interfaces.Repositories
{
    public partial interface ICampaignMessagesRepository : IBaseRepository<CampaignMessages>
    {
        Task<DLResponse<CampaignMessages>> GetByPkAsync(int id);
    }
}