//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Turuncu.SmsManagerModule.Application.Models;
using QuickCode.Turuncu.SmsManagerModule.Domain.Entities;
using QuickCode.Turuncu.SmsManagerModule.Application.Dtos;
using System.Threading.Tasks;

namespace QuickCode.Turuncu.SmsManagerModule.Application.Interfaces.Repositories
{
    public partial interface IOtpMessagesRepository : IBaseRepository<OtpMessages>
    {
        Task<DLResponse<OtpMessages>> GetByPkAsync(int id);
    }
}